"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import Navigation from "@/components/Navigation";
import TargetCard from "@/components/TargetCard";
import { ArrowLeft, Plus, Loader2, Trophy } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

interface Target {
  id: string;
  title: string;
  description?: string;
  type: "daily" | "weekly";
  progress: number;
  goal: number;
  current: number;
  completed: boolean;
  pinned?: boolean;
  deadline?: string;
}

/**
 * TargetsPage - Daily and weekly targets management
 * Mobile-first design with progress tracking
 * Features: mark targets complete, view progress, add new targets
 */
const TargetsPage = () => {
  const router = useRouter();
  const { user, isLoading: authLoading } = useAuth();
  const { toast } = useToast();
  const [targets, setTargets] = useState<Target[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<"daily" | "weekly">("daily");
  const [showAddModal, setShowAddModal] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [suggestions, setSuggestions] = useState<any[]>([]);
  const [loadingSuggestions, setLoadingSuggestions] = useState(false);
  const hasAutoGenerated = useRef(false); // Prevent multiple auto-gen runs
  const [newTarget, setNewTarget] = useState({
    title: "",
    description: "",
    type: "daily" as "daily" | "weekly",
    goal: 1,
  });

  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
    }
  }, [user, authLoading, router]);

  useEffect(() => {
    if (user) {
      fetchTargets();
    }
  }, [user]);

  const autoGenerateTargetsIfNeeded = useCallback(async () => {
    if (!user || hasAutoGenerated.current) return;
    
    hasAutoGenerated.current = true;
    console.log('[Auto-Gen] Starting...');

    const today = new Date();
    const todayString = today.toDateString();
    const lastAutoGenDate = localStorage.getItem(`lastAutoGen_${user.id}`);
    const lastWeeklyGenDate = localStorage.getItem(`lastWeeklyGen_${user.id}`);
    
    // Check if it's Monday (0 = Sunday, 1 = Monday)
    const isMonday = today.getDay() === 1;
    
    // Daily: generate every day
    const shouldGenDaily = lastAutoGenDate !== todayString;
    
    // Weekly: only generate on Mondays or if never generated
    const shouldGenWeekly = isMonday && lastWeeklyGenDate !== todayString;

    const dailyTargets = targets.filter(t => t.type === 'daily' && !t.completed);
    const weeklyTargets = targets.filter(t => t.type === 'weekly' && !t.completed);
    
    const dailyNeeded = shouldGenDaily ? Math.max(0, 3 - dailyTargets.length) : 0;
    const weeklyNeeded = shouldGenWeekly ? Math.max(0, 3 - weeklyTargets.length) : 0;
    
    console.log(`[Auto-Gen] Need ${dailyNeeded} daily, ${weeklyNeeded} weekly (Monday: ${isMonday})`);
    
    if (dailyNeeded === 0 && weeklyNeeded === 0) {
      console.log('[Auto-Gen] No targets needed');
      return;
    }
    
    const token = localStorage.getItem("token");
    const headers: HeadersInit = { "Content-Type": "application/json" };
    if (token) headers["Authorization"] = `Bearer ${token}`;

    // Generate daily targets using Gemini LLM
    if (dailyNeeded > 0) {
      try {
        console.log('[Auto-Gen] Fetching AI-powered daily suggestions...');
        const response = await fetch(`/api/targets/suggest?userId=${user.id}&type=daily&count=${dailyNeeded}`, {
          method: 'POST',
          headers,
        });
        
        if (response.ok) {
          const data = await response.json();
          const suggestions = data.suggestions || [];
          
          for (let i = 0; i < Math.min(dailyNeeded, suggestions.length); i++) {
            const suggestion = suggestions[i];
            await fetch("/api/targets", {
              method: "POST",
              headers,
              body: JSON.stringify({
                userId: user.id,
                title: suggestion.title,
                description: suggestion.description,
                type: "daily",
                goal: suggestion.goal || 1,
                completed: false,
                pinned: true,
              }),
            });
            console.log(`✅ Created AI daily: ${suggestion.title}`);
          }
        } else {
          console.error('[Auto-Gen] Failed to fetch AI suggestions, using fallbacks');
          // Fallback to hardcoded if AI fails
          const fallbacks = [
            { title: "Track 3 compulsions today", description: "Log at least 3 compulsions to build awareness", goal: 3 },
            { title: "Practice breathing exercise", description: "Do 5-minute breathing exercise when urges arise", goal: 1 },
            { title: "Delay one compulsion", description: "Wait 5 minutes before performing one compulsion today", goal: 1 },
          ];
          
          for (let i = 0; i < Math.min(dailyNeeded, fallbacks.length); i++) {
            const target = fallbacks[i];
            await fetch("/api/targets", {
              method: "POST",
              headers,
              body: JSON.stringify({
                userId: user.id,
                title: target.title,
                description: target.description,
                type: "daily",
                goal: target.goal,
                completed: false,
                pinned: true,
              }),
            });
            console.log(`✅ Created fallback daily: ${target.title}`);
          }
        }
      } catch (error) {
        console.error('[Auto-Gen] Error with AI suggestions:', error);
      }
    }

    // Create weekly targets directly with static defaults (only on Mondays)
    if (weeklyNeeded > 0) {
      const weeklyDefaults = [
        { title: "Weekly compulsion tracking", description: "Log at least 10 compulsions this week", goal: 10 },
        { title: "Weekly mindfulness practice", description: "Complete 4 breathing or meditation sessions this week", goal: 4 },
        { title: "Weekly exposure goal", description: "Face 2 triggering situations without ritualizing", goal: 2 },
      ];

      for (let i = 0; i < Math.min(weeklyNeeded, weeklyDefaults.length); i++) {
        const target = weeklyDefaults[i];
        await fetch("/api/targets", {
          method: "POST",
          headers,
          body: JSON.stringify({
            userId: user.id,
            title: target.title,
            description: target.description,
            type: "weekly",
            goal: target.goal,
            completed: false,
            pinned: true,
          }),
        });
        console.log(`✅ Created weekly: ${target.title}`);
      }
      localStorage.setItem(`lastWeeklyGen_${user.id}`, todayString);
    }

    await fetchTargets();
    localStorage.setItem(`lastAutoGen_${user.id}`, todayString);
    console.log('[Auto-Gen] Complete');
  }, [user, targets]);

  // Auto-generate targets when targets are loaded (only once per mount)
  useEffect(() => {
    if (!authLoading && user && !isLoading && !hasAutoGenerated.current) {
      console.log('[Targets Page] Checking if auto-generation needed...');
      autoGenerateTargetsIfNeeded();
    }
  }, [authLoading, user, isLoading]); // DO NOT include autoGenerateTargetsIfNeeded - it changes when targets change!


  const autoGenerateTargets = async (type: 'daily' | 'weekly', count: number) => {
    if (!user || count <= 0) return;

    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }
      
      console.log(`[Auto-Gen] Requesting ${count} ${type} suggestions...`);
      
      // Get AI suggestions
      const suggestResponse = await fetch(`/api/targets/suggest?userId=${user.id}&type=${type}`, {
        method: "POST",
        headers,
      });
      
      if (!suggestResponse.ok) {
        console.error('[Auto-Gen] Suggest API failed:', suggestResponse.status);
        return;
      }
      
      const data = await suggestResponse.json();
      const suggestions = (data.suggestions || []).slice(0, count);
      
      console.log(`[Auto-Gen] Received ${suggestions.length} suggestions:`, suggestions.map(s => ({ title: s.title, type: s.type })));

      // Filter to ensure we only create targets of the requested type
      const filteredSuggestions = suggestions.filter(s => s.type === type).slice(0, count);
      console.log(`[Auto-Gen] Filtered to ${filteredSuggestions.length} ${type} suggestions`);

      // Auto-add suggestions with pinned=true (all auto-generated targets are pinned)
      for (const suggestion of filteredSuggestions) {
        const response = await fetch("/api/targets", {
          method: "POST",
          headers,
          body: JSON.stringify({
            userId: user.id,
            title: suggestion.title,
            description: suggestion.description,
            type: suggestion.type,
            goal: suggestion.goal,
            completed: false,
            pinned: true, // Auto-generated = always pinned
          }),
        });
        
        if (!response.ok) {
          console.error("Failed to create auto-generated target");
        } else {
          const newTarget = await response.json();
          console.log(`✅ Auto-generated ${type} target:`, newTarget.title, `| Type: ${newTarget.type} | Pinned:`, newTarget.pinned);
        }
      }

      // DON'T refresh here - let the parent function refresh once at the end
      
    } catch (error) {
      console.error("Failed to auto-generate targets:", error);
    }
  };

  const fetchTargets = async () => {
    if (!user) return;
    
    setIsLoading(true);
    
    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = {};
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }
      
      const response = await fetch(`/api/targets?userId=${user.id}`, { headers });
      if (response.ok) {
        const data = await response.json();
        // Transform API data to match component expectations
        const transformedTargets: Target[] = (data.targets || []).map((t: any) => ({
          id: t._id || t.id,
          title: t.title,
          description: t.description,
          type: t.type,
          progress: t.completed ? 100 : 0,
          goal: t.goal || 1,
          current: t.completed ? (t.goal || 1) : 0,
          completed: t.completed,
          pinned: t.pinned || false,
          deadline: t.type === "daily" ? "Today, 11:59 PM" : "Sunday, 11:59 PM",
        }));
        setTargets(transformedTargets);
      } else {
        throw new Error("Failed to fetch targets");
      }
    } catch (error) {
      console.error("Failed to fetch targets:", error);
      setTargets([]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCompleteTarget = async (targetId: string) => {
    const target = targets.find((t) => t.id === targetId);
    if (!target || !user) return;

    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }
      
      const response = await fetch("/api/targets", {
        method: "POST",
        headers,
        body: JSON.stringify({
          userId: user.id,
          title: target.title,
          description: target.description,
          type: target.type,
          goal: target.goal,
          completed: true,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to complete target");
      }

      // Update local state
      setTargets((prev) =>
        prev.map((t) =>
          t.id === targetId
            ? { ...t, completed: true, progress: 100, current: t.goal }
            : t
        )
      );
    } catch (error) {
      console.error("Failed to complete target:", error);
      toast({
        title: "Update failed",
        description: "Failed to mark target as complete. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleDeleteTarget = async (targetId: string) => {
    if (!user) return;

    // Optimistically remove from UI
    const deletedTarget = targets.find(t => t.id === targetId);
    setTargets((prev) => prev.filter((t) => t.id !== targetId));

    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = {};
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }

      const response = await fetch(`/api/targets/${targetId}`, {
        method: "DELETE",
        headers,
      });

      if (!response.ok) {
        throw new Error("Failed to delete target");
      }
    } catch (error) {
      console.error("Failed to delete target:", error);
      // Restore on error
      if (deletedTarget) {
        setTargets((prev) => [...prev, deletedTarget]);
      }
      toast({
        title: "Delete failed",
        description: "Failed to delete target. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handlePinTarget = async (targetId: string, pinned: boolean) => {
    if (!user) return;

    // Optimistically update UI
    const target = targets.find(t => t.id === targetId);
    setTargets((prev) =>
      prev.map((t) => (t.id === targetId ? { ...t, pinned } : t))
    );

    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }

      const response = await fetch(`/api/targets/pin/${targetId}`, {
        method: "PATCH",
        headers,
        body: JSON.stringify({ pinned }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to pin target");
      }
    } catch (error: any) {
      console.error("Failed to pin target:", error);
      // Revert on error
      setTargets((prev) =>
        prev.map((t) => (t.id === targetId ? { ...t, pinned: !pinned } : t))
      );
      alert(error.message || "Failed to update pin status. Please try again.");
    }
  };

  const handleAddTarget = () => {
    if (!newTarget.title.trim()) return;

    const target: Target = {
      id: `t${Date.now()}`,
      title: newTarget.title,
      description: newTarget.description,
      type: newTarget.type,
      progress: 0,
      goal: newTarget.goal,
      current: 0,
      completed: false,
      deadline: newTarget.type === "daily" ? "Today, 11:59 PM" : "Sunday, 11:59 PM",
    };

    setTargets((prev) => [...prev, target]);
    setShowAddModal(false);
    setNewTarget({
      title: "",
      description: "",
      type: "daily",
      goal: 1,
    });
  };

  const handleGetSuggestions = async (type?: 'daily' | 'weekly') => {
    if (!user) return;
    
    setLoadingSuggestions(true);
    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = {};
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }
      
      const typeParam = type ? `&type=${type}` : '';
      const response = await fetch(`/api/targets/suggest?userId=${user.id}${typeParam}`, {
        method: "POST",
        headers,
      });
      if (response.ok) {
        const data = await response.json();
        setSuggestions(data.suggestions || []);
        setShowSuggestions(true);
      } else {
        throw new Error("Failed to get suggestions");
      }
    } catch (error) {
      console.error("Failed to get suggestions:", error);
      toast({
        title: "Generation failed",
        description: "Failed to generate suggestions. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoadingSuggestions(false);
    }
  };

  const handleAddSuggestedTarget = async (suggestion: any, silent = false) => {
    if (!user) return;
    
    try {
      const token = localStorage.getItem("token");
      const headers: HeadersInit = { "Content-Type": "application/json" };
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }

      // In silent mode (auto-generation), always pin
      // In manual mode, check if under limit
      let shouldPin = silent;
      if (!silent) {
        const sameTypeTargets = targets.filter(t => t.type === suggestion.type && t.pinned);
        const maxPinned = suggestion.type === 'daily' ? 3 : 3; // Both are now 3
        shouldPin = sameTypeTargets.length < maxPinned;
      }
      
      const response = await fetch("/api/targets", {
        method: "POST",
        headers,
        body: JSON.stringify({
          userId: user.id,
          title: suggestion.title,
          description: suggestion.description,
          type: suggestion.type,
          goal: suggestion.goal,
          completed: false,
          pinned: shouldPin, // Auto-pin if silent mode or under limit
        }),
      });

      if (response.ok) {
        if (!silent) {
          await fetchTargets();
          setSuggestions((prev) => prev.filter((s) => s.title !== suggestion.title));
        }
      }
    } catch (error) {
      console.error("Failed to add target:", error);
      if (!silent) {
        alert("Failed to add target. Please try again.");
      }
    }
  };

  const dailyTargets = targets.filter((t) => t.type === "daily");
  const weeklyTargets = targets.filter((t) => t.type === "weekly");
  
  const completedDaily = dailyTargets.filter((t) => t.completed).length;
  const completedWeekly = weeklyTargets.filter((t) => t.completed).length;

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-12 h-12 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Page Header */}
      <header className="bg-card border-b border-border shadow-soft sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4 max-w-4xl">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => router.push("/")}
                aria-label="Go back"
              >
                <ArrowLeft className="w-5 h-5" />
              </Button>
              <div>
                <h1 className="text-xl font-medium text-foreground">Targets</h1>
                <p className="text-sm text-muted-foreground">Track your daily & weekly goals</p>
              </div>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowAddModal(true)}
              className="gap-2 border-border"
            >
              <Plus className="w-4 h-4" />
              <span className="hidden sm:inline">Add</span>
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-6 max-w-3xl">
        {/* AI Suggestions Section */}
        {showSuggestions && suggestions.length > 0 && (
          <Card className="p-4 mb-6 bg-gradient-to-br from-purple-50 to-pink-50 border-purple-200">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-purple-900">🎯 AI Suggested Targets</h3>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowSuggestions(false)}
                className="text-purple-600 hover:text-purple-700"
              >
                ✕
              </Button>
            </div>
            <div className="space-y-3">
              {suggestions.map((suggestion, idx) => (
                <div
                  key={idx}
                  className="p-3 bg-white rounded-lg border border-purple-200 shadow-sm"
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1">
                      <h4 className="text-sm font-medium text-gray-900">{suggestion.title}</h4>
                      <p className="text-xs text-gray-600 mt-1">{suggestion.description}</p>
                      <p className="text-xs text-purple-600 mt-2 italic">
                        💡 {suggestion.reasoning}
                      </p>
                    </div>
                    <Button
                      size="sm"
                      onClick={() => handleAddSuggestedTarget(suggestion)}
                      className="shrink-0 text-xs"
                    >
                      Add
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        )}
        {/* Stats Overview */}
        <div className="grid grid-cols-2 gap-4 mb-6">
          <Card className="p-4 bg-card border-border shadow-soft">
            <div className="flex items-center gap-2 mb-2">
              <Trophy className="w-5 h-5 text-primary" />
              <span className="text-sm font-medium text-muted-foreground">Daily</span>
            </div>
            <p className="text-2xl font-semibold text-foreground">
              {completedDaily}/{dailyTargets.length}
            </p>
            <p className="text-xs text-muted-foreground">completed today</p>
            {dailyTargets.length > 0 && (
              <div className="mt-2 bg-muted h-1.5 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-primary transition-all duration-300"
                  style={{ width: `${(completedDaily / dailyTargets.length) * 100}%` }}
                />
              </div>
            )}
          </Card>

          <Card className="p-4 bg-card border-border shadow-soft">
            <div className="flex items-center gap-2 mb-2">
              <Trophy className="w-5 h-5 text-success" />
              <span className="text-sm font-medium text-muted-foreground">Weekly</span>
            </div>
            <p className="text-2xl font-semibold text-foreground">
              {completedWeekly}/{weeklyTargets.length}
            </p>
            <p className="text-xs text-muted-foreground">completed this week</p>
            {weeklyTargets.length > 0 && (
              <div className="mt-2 bg-muted h-1.5 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-success transition-all duration-300"
                  style={{ width: `${(completedWeekly / weeklyTargets.length) * 100}%` }}
                />
              </div>
            )}
          </Card>
        </div>

        {/* Motivational Progress Card */}
        {(dailyTargets.length > 0 || weeklyTargets.length > 0) && (
          <Card className="p-5 mb-6 bg-gradient-to-br from-green-50 to-emerald-50 border-green-200">
            <div className="flex items-start gap-3">
              <div className="text-2xl">
                {completedDaily + completedWeekly === dailyTargets.length + weeklyTargets.length 
                  ? "🎉" 
                  : completedDaily + completedWeekly > 0 
                    ? "💪" 
                    : "🎯"}
              </div>
              <div className="flex-1">
                <h3 className="text-sm font-semibold text-green-900 mb-1">
                  {completedDaily + completedWeekly === dailyTargets.length + weeklyTargets.length
                    ? "Amazing work! All targets completed!"
                    : completedDaily + completedWeekly > 0
                      ? "Great progress! Keep going!"
                      : "Ready to start? Pick a target to begin!"}
                </h3>
                <p className="text-xs text-green-700">
                  {completedDaily + completedWeekly === dailyTargets.length + weeklyTargets.length
                    ? "You've completed all your targets. Consider setting new ones to maintain momentum."
                    : completedDaily + completedWeekly > 0
                      ? `You've completed ${completedDaily + completedWeekly} out of ${dailyTargets.length + weeklyTargets.length} targets. Every step forward counts!`
                      : "Start with one small target. Progress happens one step at a time."}
                </p>
              </div>
            </div>
          </Card>
        )}

        {/* Tabs for Daily/Weekly */}
        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "daily" | "weekly")}>
          <TabsList className="grid w-full grid-cols-2 mb-6 bg-muted">
            <TabsTrigger value="daily">Daily Targets</TabsTrigger>
            <TabsTrigger value="weekly">Weekly Targets</TabsTrigger>
          </TabsList>

          {/* Daily Targets */}
          <TabsContent value="daily" className="space-y-4">
            {/* AI Suggestions Button for Daily */}
            <Button
              variant="default"
              size="sm"
              onClick={() => handleGetSuggestions('daily')}
              disabled={loadingSuggestions}
              className="w-full gap-2 bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 mb-4"
            >
              {loadingSuggestions ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Analyzing patterns...
                </>
              ) : (
                <>
                  ✨ Get Daily AI Suggestions
                </>
              )}
            </Button>
            
            {dailyTargets.length === 0 ? (
              <Card className="p-8 text-center bg-card border-border">
                <p className="text-muted-foreground">No daily targets set yet.</p>
                <Button
                  onClick={() => {
                    setNewTarget({ ...newTarget, type: "daily" });
                    setShowAddModal(true);
                  }}
                  className="mt-4 bg-primary hover:bg-primary/90"
                >
                  Create Your First Target
                </Button>
              </Card>
            ) : (
              dailyTargets.map((target) => (
                <TargetCard
                  key={target.id}
                  target={target}
                  onComplete={handleCompleteTarget}
                  onDelete={handleDeleteTarget}
                  onPin={handlePinTarget}
                />
              ))
            )}
          </TabsContent>

          {/* Weekly Targets */}
          <TabsContent value="weekly" className="space-y-4">
            {/* AI Suggestions Button for Weekly */}
            <Button
              variant="default"
              size="sm"
              onClick={() => handleGetSuggestions('weekly')}
              disabled={loadingSuggestions}
              className="w-full gap-2 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 mb-4"
            >
              {loadingSuggestions ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Analyzing patterns...
                </>
              ) : (
                <>
                  ✨ Get Weekly AI Suggestions
                </>
              )}
            </Button>
            
            {weeklyTargets.length === 0 ? (
              <Card className="p-8 text-center bg-card border-border">
                <p className="text-muted-foreground">No weekly targets set yet.</p>
                <Button
                  onClick={() => {
                    setNewTarget({ ...newTarget, type: "weekly" });
                    setShowAddModal(true);
                  }}
                  className="mt-4 bg-success hover:bg-success/90 text-success-foreground"
                >
                  Create Your First Target
                </Button>
              </Card>
            ) : (
              weeklyTargets.map((target) => (
                <TargetCard
                  key={target.id}
                  target={target}
                  onComplete={handleCompleteTarget}
                  onDelete={handleDeleteTarget}
                  onPin={handlePinTarget}
                />
              ))
            )}
          </TabsContent>
        </Tabs>
      </main>

      {/* Add Target Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/20 backdrop-blur-sm animate-fadeIn">
          <Card className="w-full max-w-md p-6 shadow-soft-lg bg-card border-border">
            <h3 className="text-lg font-medium text-foreground mb-4">
              Create New Target
            </h3>
            
            <div className="space-y-4">
              {/* Title */}
              <div>
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wide block mb-2">
                  Target Title
                </label>
                <input
                  type="text"
                  value={newTarget.title}
                  onChange={(e) => setNewTarget({ ...newTarget, title: e.target.value })}
                  placeholder="e.g., Limit checking to 2 times"
                  className="w-full p-3 text-sm border border-border rounded-md bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/20 transition-calm"
                />
              </div>

              {/* Description */}
              <div>
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wide block mb-2">
                  Description (optional)
                </label>
                <textarea
                  value={newTarget.description}
                  onChange={(e) => setNewTarget({ ...newTarget, description: e.target.value })}
                  placeholder="Add more details..."
                  className="w-full p-3 text-sm border border-border rounded-md bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/20 resize-none transition-calm"
                  rows={2}
                />
              </div>

              {/* Type */}
              <div>
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wide block mb-2">
                  Target Type
                </label>
                <div className="flex gap-2">
                  <button
                    onClick={() => setNewTarget({ ...newTarget, type: "daily" })}
                    className={`flex-1 p-3 text-sm rounded-md border transition-calm ${
                      newTarget.type === "daily"
                        ? "bg-primary/10 border-primary text-primary font-medium"
                        : "bg-card border-border text-muted-foreground hover:bg-muted"
                    }`}
                  >
                    Daily
                  </button>
                  <button
                    onClick={() => setNewTarget({ ...newTarget, type: "weekly" })}
                    className={`flex-1 p-3 text-sm rounded-md border transition-calm ${
                      newTarget.type === "weekly"
                        ? "bg-success/10 border-success text-success-foreground font-medium"
                        : "bg-card border-border text-muted-foreground hover:bg-muted"
                    }`}
                  >
                    Weekly
                  </button>
                </div>
              </div>

              {/* Goal */}
              <div>
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wide block mb-2">
                  Goal (times to complete)
                </label>
                <input
                  type="number"
                  min="1"
                  value={newTarget.goal}
                  onChange={(e) => setNewTarget({ ...newTarget, goal: parseInt(e.target.value) || 1 })}
                  className="w-full p-3 text-sm border border-border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary/20 transition-calm"
                />
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3 mt-6">
              <Button
                onClick={() => setShowAddModal(false)}
                variant="outline"
                className="flex-1 border-border"
              >
                Cancel
              </Button>
              <Button
                onClick={handleAddTarget}
                disabled={!newTarget.title.trim()}
                className="flex-1 bg-primary hover:bg-primary/90"
              >
                Create Target
              </Button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
};

export default TargetsPage;

// Commit message: feat: create TargetsPage with daily/weekly targets and progress tracking
